import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:gridview/core/media/media_image_loader.dart';
import 'package:gridview/core/media/media_load_outcome.dart';
import 'package:gridview/core/preferences/preference_values.dart';
import 'package:gridview/features/explore/presentation/explore_screen.dart';
import 'package:gridview/features/settings/presentation/acknowledgements_screen.dart';
import 'package:gridview/features/shared/domain/entities/enums.dart';
import 'package:gridview/features/shared/domain/entities/media.dart';
import 'package:gridview/features/shared/domain/entities/season_card.dart';

import '../support/entity_fixtures.dart';
import '../support/fake_entity_repository.dart';
import '../support/media_fixtures.dart';
import '../support/router_harness.dart';
import '../support/synthetic_png.dart';

/// Visual coverage for Phase 8B media.
///
/// Deliberately **representative, not exhaustive**: a loaded state, a fallback
/// state and a failure state in each theme is enough to catch a regression in
/// how media sits in a layout. Every possible combination of slot, category and
/// outcome would multiply the baseline count without multiplying what the images
/// actually tell a reviewer.
///
/// Everything that could make an image non-deterministic is pinned: locale,
/// theme, platform brightness, surface size, text scale, clock, device time
/// zone, preferences, **loader state and cache state**. The loader serves every
/// request straight from its cache, so no fade animation is ever captured
/// mid-flight and no frame depends on timing.
///
/// The imagery is generated by `synthetic_png.dart` — flat geometric bands. It is
/// not a driver photograph, a team logo, a Formula 1 mark or circuit
/// photography, because GridView has the right to use none of those.
const Size _device = Size(390, 844);
final DateTime _clock = DateTime.utc(2026, 7, 18, 12, 10);

late Directory _tmp;
late File _square;
late File _wide;

/// Serves every request from cache, so a golden never captures a fade.
class _CachedLoader implements MediaImageLoader {
  _CachedLoader(this.file);

  final File file;

  @override
  Future<File?> cached(MediaImageRequest request) async => file;

  @override
  Future<MediaLoadOutcome> load(MediaImageRequest request) async =>
      MediaLoaded(file: file, fromCache: true);
}

/// Fails every request, so a golden captures the fallback rather than an image.
class _FailingLoader implements MediaImageLoader {
  @override
  Future<File?> cached(MediaImageRequest request) async => null;

  @override
  Future<MediaLoadOutcome> load(MediaImageRequest request) async =>
      const MediaLoadFailed(MediaFailureKind.network);
}

MediaAsset _portrait(String driverId) =>
    portraitAsset(id: '$driverId-portrait-v1', owner: driverId);

MediaAsset _logo(String constructorId) => MediaAsset(
  id: '$constructorId-logo-v1',
  entityType: MediaEntityType.constructor,
  entityId: constructorId,
  category: MediaCategory.logo,
  format: MediaFormat.png,
  version: 'v1',
  aspectRatio: 1,
  variants: MediaVariants(
    thumbnail: variant(
      testMediaUrl('constructors', constructorId, 'v1', 'thumbnail'),
      width: 160,
      height: 160,
    ),
    detail: variant(
      testMediaUrl('constructors', constructorId, 'v1', 'detail'),
      width: 960,
      height: 960,
    ),
  ),
);

MediaAsset _layout(String circuitId) => MediaAsset(
  id: '$circuitId-layout-v1',
  entityType: MediaEntityType.circuit,
  entityId: circuitId,
  category: MediaCategory.circuitLayout,
  format: MediaFormat.png,
  version: 'v1',
  aspectRatio: 16 / 9,
  variants: MediaVariants(
    thumbnail: variant(
      testMediaUrl('circuits', circuitId, 'v1', 'thumbnail'),
      width: 160,
      height: 90,
    ),
    detail: variant(
      testMediaUrl('circuits', circuitId, 'v1', 'detail'),
      width: 960,
      height: 540,
    ),
  ),
);

List<SeasonDriverCard> _drivers({bool withMedia = true}) => <SeasonDriverCard>[
  for (int i = 0; i < 6; i++)
    driverCard(
      driverId: 'test-shape-${i + 1}',
      name: 'Test Shape ${i + 1}',
      order: i,
      raceNumber: i + 1,
      teamName: 'Test Team ${(i ~/ 2) + 1}',
      position: i + 1,
      points: (6 - i) * 10,
      media: withMedia
          ? entityMediaOf(<MediaAsset>[
              _portrait('test-shape-${i + 1}'),
            ], ownerId: 'test-shape-${i + 1}')
          : null,
    ),
];

List<SeasonTeamCard> _teams() => <SeasonTeamCard>[
  for (int i = 0; i < 5; i++)
    teamCard(
      constructorId: 'test-team-${i + 1}',
      stableName: 'Test Team ${i + 1}',
      seasonName: 'Test Team ${i + 1} Racing',
      order: i,
      position: i + 1,
      points: (5 - i) * 25,
      media: entityMediaOf(
        <MediaAsset>[_logo('test-team-${i + 1}')],
        ownerType: MediaEntityType.constructor,
        ownerId: 'test-team-${i + 1}',
      ),
    ),
];

List<SeasonCircuitCard> _circuits() => <SeasonCircuitCard>[
  for (int i = 0; i < 5; i++)
    circuitCard(
      circuitId: 'test-circuit-${i + 1}',
      name: 'Test Circuit ${i + 1}',
      order: i + 1,
      locality: 'Test Locality',
      country: 'Testland',
      lengthMeters: 5000 + i * 100,
      media: entityMediaOf(
        <MediaAsset>[_layout('test-circuit-${i + 1}')],
        ownerType: MediaEntityType.circuit,
        ownerId: 'test-circuit-${i + 1}',
      ),
    ),
];

/// Lets every rendered image finish decoding before the frame is captured.
///
/// `Image.file` reads from disk and decodes asynchronously, which a widget
/// test's fake async never completes on its own. Without this a golden would
/// capture the placeholder and silently pass as though it were the loaded state
/// — the worst kind of green.
///
/// Each rendered `Image`'s own provider is resolved and awaited, rather than
/// waiting a fixed interval or calling `precacheImage`. A fixed delay does not
/// actually guarantee the frame arrived — it produced goldens showing an empty
/// slot, which is exactly the silent green this helper exists to prevent — and
/// passing an `Element` to `precacheImage` deadlocks on this setup.
///
/// Resolving the widget's own provider also means the `ResizeImage` wrapper the
/// component adds for decode sizing is honoured, so what is primed is what is
/// painted.
Future<void> _settleImages(WidgetTester tester) async {
  // Alternating a real-time window with a frame pump, rather than awaiting
  // inside `runAsync`. The read and the decode only progress under real async,
  // but the decoded frame is only *delivered* by a pump, so neither on its own
  // is enough: a fixed delay followed by pumps produced goldens with an empty
  // slot, and awaiting the image stream inside `runAsync` deadlocks because no
  // frame is pumped while it waits.
  for (int i = 0; i < 12; i++) {
    await tester.runAsync(
      () => Future<void>.delayed(const Duration(milliseconds: 50)),
    );
    await tester.pump();
    if (_allImagesPainted(tester)) break;
  }
  await tester.pump();
}

/// Whether every `Image` in the tree has actually painted a frame.
///
/// Asserted rather than assumed: a golden that captures a placeholder where a
/// picture belongs would pass forever while showing the wrong thing.
bool _allImagesPainted(WidgetTester tester) {
  final Iterable<RenderObject> images = find
      .byType(RawImage)
      .evaluate()
      .map((Element e) => e.renderObject!);
  if (images.isEmpty) return false;
  return images.every((RenderObject r) => (r as RenderImage).image != null);
}

Future<void> _pumpExplore(
  WidgetTester tester, {
  required String location,
  required MediaImageLoader loader,
  AppPreferences preferences = AppPreferences.defaults,
  List<SeasonDriverCard>? drivers,
}) async {
  await pumpApp(
    tester,
    initialLocation: location,
    surfaceSize: _device,
    clock: _clock,
    preferences: preferences,
    platformBrightness: Brightness.dark,
    disableAnimations: true,
    mediaLoader: loader,
    drivers: FakeDriverRepository(
      cards: (int season) => drivers ?? _drivers(),
      profile: (int season, String driverId) =>
          driverProfileFixture(season: season, driverId: driverId),
    ),
    constructors: FakeConstructorRepository(
      cards: (int season) => _teams(),
      profile: (int season, String constructorId) =>
          teamProfileFixture(season: season, constructorId: constructorId),
    ),
    circuits: FakeCircuitRepository(
      cards: (int season) => _circuits(),
      profile: (int season, String circuitId) =>
          circuitProfileFixture(season: season, circuitId: circuitId),
    ),
  );
  await _settleImages(tester);
}

void main() {
  setUpAll(() {
    _tmp = Directory.systemTemp.createTempSync('gv_media_goldens');
    _square = writePng(_tmp, 'square.png', bandedPng(160, 160));
    _wide = writePng(_tmp, 'wide.png', bandedPng(160, 90, bands: 3));
  });

  tearDownAll(() {
    // Best effort: the decoded images may still hold the files open, and on
    // Windows that makes the delete fail. A leftover temp directory is not a
    // test failure.
    try {
      if (_tmp.existsSync()) _tmp.deleteSync(recursive: true);
    } on FileSystemException {
      // Ignored deliberately.
    }
  });

  group('Explore rows with media', () {
    testWidgets('golden: explore drivers with loaded portraits', (
      WidgetTester tester,
    ) async {
      await _pumpExplore(
        tester,
        location: '/explore',
        loader: _CachedLoader(_square),
      );
      await expectLater(
        find.byType(ExploreScreen),
        matchesGoldenFile('goldens/explore_drivers_media_dark.png'),
      );
    });

    testWidgets('golden: explore drivers with no media at all', (
      WidgetTester tester,
    ) async {
      // The fallback every row falls back to, at the same size as the loaded
      // state above: the two images must differ only inside the leading slot.
      await _pumpExplore(
        tester,
        location: '/explore',
        loader: _CachedLoader(_square),
        drivers: _drivers(withMedia: false),
      );
      await expectLater(
        find.byType(ExploreScreen),
        matchesGoldenFile('goldens/explore_drivers_no_media.png'),
      );
    });

    testWidgets('golden: explore drivers when every image fails', (
      WidgetTester tester,
    ) async {
      // Must be visually identical to the no-media golden: a user cannot be
      // shown the difference between "there is no picture" and "the picture
      // did not arrive".
      await _pumpExplore(
        tester,
        location: '/explore',
        loader: _FailingLoader(),
      );
      await expectLater(
        find.byType(ExploreScreen),
        matchesGoldenFile('goldens/explore_drivers_media_failed.png'),
      );
    });

    testWidgets('golden: explore teams with loaded marks', (
      WidgetTester tester,
    ) async {
      await _pumpExplore(
        tester,
        location: '/explore/teams',
        loader: _CachedLoader(_square),
      );
      await expectLater(
        find.byType(ExploreScreen),
        matchesGoldenFile('goldens/explore_teams_media_dark.png'),
      );
    });

    testWidgets('golden: explore circuits with loaded layouts', (
      WidgetTester tester,
    ) async {
      await _pumpExplore(
        tester,
        location: '/explore/circuits',
        loader: _CachedLoader(_wide),
      );
      await expectLater(
        find.byType(ExploreScreen),
        matchesGoldenFile('goldens/explore_circuits_media_dark.png'),
      );
    });

    testWidgets('golden: explore drivers with loaded portraits, light theme', (
      WidgetTester tester,
    ) async {
      await _pumpExplore(
        tester,
        location: '/explore',
        loader: _CachedLoader(_square),
        preferences: const AppPreferences(
          language: AppLanguagePreference.system,
          theme: AppThemePreference.light,
          timeDisplay: TimeDisplayPreference.device,
        ),
      );
      await expectLater(
        find.byType(ExploreScreen),
        matchesGoldenFile('goldens/explore_drivers_media_light.png'),
      );
    });
  });

  group('acknowledgements', () {
    testWidgets('golden: acknowledgements with media credits', (
      WidgetTester tester,
    ) async {
      await pumpApp(
        tester,
        initialLocation: '/settings/acknowledgements',
        surfaceSize: _device,
        clock: _clock,
        platformBrightness: Brightness.dark,
        disableAnimations: true,
        mediaAttributions: const <MediaAttribution>[
          MediaAttribution(
            category: MediaCategory.portrait,
            attribution: 'GridView synthetic fixture',
            license: 'GridView-owned synthetic fixture',
          ),
          MediaAttribution(
            category: MediaCategory.circuitLayout,
            attribution: 'GridView synthetic layout',
            license: 'GridView-owned synthetic fixture',
          ),
        ],
      );
      await expectLater(
        find.byType(AcknowledgementsScreen),
        matchesGoldenFile('goldens/acknowledgements_with_credits.png'),
      );
    });
  });
}
