import sharp from 'sharp';

import type {
  MediaRightsRecord,
  MediaRightsRegister,
  SourceMasterProbe,
} from '../../scripts/media/rights.ts';

/// A synthetic test master: flat colour bands on a solid ground.
///
/// **Generated, never copied.** Nothing in this repository's test data is a
/// driver photograph, a team logo, a Formula 1 mark or circuit photography, and
/// nothing here comes from a provider URL. These images are unmistakably
/// artificial geometry, which is all a processing test needs and the only thing
/// GridView has the right to use.
export async function syntheticMaster(
  width: number,
  height: number,
  options: { readonly alpha?: boolean } = {},
): Promise<Buffer> {
  const channels = options.alpha === true ? 4 : 3;
  const band = Math.max(1, Math.floor(height / 4));
  const pixels = Buffer.alloc(width * height * channels);
  for (let y = 0; y < height; y++) {
    const shade = ((Math.floor(y / band) + 1) * 48) % 256;
    for (let x = 0; x < width; x++) {
      const offset = (y * width + x) * channels;
      pixels[offset] = shade;
      pixels[offset + 1] = (x * 3) % 256;
      pixels[offset + 2] = 128;
      if (channels === 4) pixels[offset + 3] = 255;
    }
  }
  return sharp(pixels, { raw: { width, height, channels } }).png().toBuffer();
}

/// A synthetic master carrying an EXIF orientation flag, for the rotation test.
export async function rotatedSyntheticMaster(
  width: number,
  height: number,
): Promise<Buffer> {
  return sharp(await syntheticMaster(width, height))
    .withMetadata({ orientation: 6 })
    .jpeg()
    .toBuffer();
}

export function rightsRecord(
  overrides: Partial<MediaRightsRecord> = {},
): MediaRightsRecord {
  return {
    assetId: 'test-shape-portrait-v1',
    entityType: 'driver',
    entityId: 'test-shape',
    category: 'portrait',
    version: 'v1',
    sourceFile: 'masters/test-shape.png',
    sourceReference: 'Generated by the GridView test suite.',
    rightsHolder: 'GridView (synthetic test asset)',
    licenceBasis: 'GridView-owned synthetic fixture',
    attribution: 'GridView synthetic fixture',
    attributionPlacement: 'central',
    territories: ['WORLDWIDE'],
    expiresAt: null,
    approvedForCommercialUse: true,
    derivativesAllowed: true,
    approvalStatus: 'approved',
    provenanceNote:
      'Synthetic fixture generated in-test; no third-party rights.',
    ...overrides,
  };
}

export function register(
  ...assets: readonly MediaRightsRecord[]
): MediaRightsRegister {
  return { kind: 'media-rights', status: 'mock', assets };
}

/// A probe that reports every master present and valid.
export const presentMaster: SourceMasterProbe = async () => ({
  exists: true,
  valid: true,
});

export const missingMaster: SourceMasterProbe = async () => ({
  exists: false,
  valid: false,
});

export const corruptMaster: SourceMasterProbe = async () => ({
  exists: true,
  valid: false,
});

/// An in-memory object store, so publication is exercised end to end with no
/// bucket, no credential and no network.
export class FakeObjectStore {
  readonly objects = new Map<string, { contentHash: string; bytes: Buffer }>();
  readonly puts: string[] = [];

  async head(objectKey: string): Promise<{ contentHash: string } | null> {
    const existing = this.objects.get(objectKey);
    return existing ? { contentHash: existing.contentHash } : null;
  }

  async put(objectKey: string, bytes: Buffer): Promise<void> {
    this.puts.push(objectKey);
    const { createHash } = await import('node:crypto');
    this.objects.set(objectKey, {
      contentHash: createHash('sha256').update(bytes).digest('hex'),
      bytes,
    });
  }

  /// Seeds a key with content that differs from anything the pipeline produces,
  /// so an overwrite attempt is a genuine conflict.
  seedConflicting(objectKey: string): void {
    this.objects.set(objectKey, {
      contentHash: 'conflicting-content-hash',
      bytes: Buffer.from('different'),
    });
  }
}

export const testUse = {
  commercial: true,
  territory: 'WORLDWIDE',
  at: new Date('2026-08-01T00:00:00.000Z'),
} as const;
